vector<string> lvl1;
vector<string> lvl2;

void batmove(int,int);
void jumpside(int);
void jump();
void checkmissile();

void drawlvlsquare(int x, int y, char color)
{
 int size_of_box=level1.sizeofbox;
 x*=size_of_box;y*=size_of_box;
 if (color=='G')   glColor3f(0.5,0.5,0.5);
 else if (color=='B')   glColor3f(0.0,0.0,1.0);
 else if (color=='W')   glColor3f(1.0,1.0,1.0);
 else glColor3f(0.0,0.0,1.0);
 glBegin(GL_POLYGON);
        glVertex2f(x, y); 
        glVertex2f(x, y+size_of_box);
        glVertex2f(x+size_of_box, y+size_of_box);
        glVertex2f(x+size_of_box, y);
 glEnd();
}

void batlvl1init()
{
  lvl1.push_back("GGGBBGGGGGBBBBWWWWBBGGGGGWWGGGWWWGGGGGGGGGG");
  lvl1.push_back("GGGGGGGGGGGGGGGGGGGGGGGGGBBBBBBBBBBBBBBBGGG");
  lvl1.push_back("GGGGGGGGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBBGGG");
  lvl1.push_back("BBBBGGGGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBBGGG");
  lvl1.push_back("BBBBBBBGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGG");
  lvl1.push_back("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGGG");
  lvl1.push_back("BBBBBBBBBBBBBBGGGGGGGGGGGGBBBBBBBBGGGGGGGGG");
  lvl1.push_back("BBBBBBBBBBBBBBBBBGGGGGGBBBBBBGGGGGGGGGGGGGG");
  lvl1.push_back("GGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGGGGGG");
  lvl1.push_back("GGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGG");
  lvl1.push_back("GGGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGG");
  lvl1.push_back("GGGGGGGGGGGGGGGGGGBBBBBBBBBBBBBBBBBBBGGGGGG");
  lvl1.push_back("BBBBBBBBGGGGGGGGGGGGGGGBBBBBBBBBBBBBBGGGGGG");
  lvl1.push_back("BBBBBBBBBBBBBBBBBBBGGGGGGGGGBBBBBBBBBBGGGGG");
  lvl1.push_back("BBBBBBBBBBBBBBBBBBBBBBBBBBGGGGBBBBBBBBGGGGG");
  lvl1.push_back("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGBBBBBBBBGGGG");
  lvl1.push_back("BBBBGGGGGGBBBGGGGGGGGGBBBBBBBBBGGGGGBBBGGGG");
  lvl1.push_back("GGGGGGGGGGBBBBBBBBBGGGGBBBBBBBBBBBBBBBBGGGG");
  lvl1.push_back("GGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGG");
  lvl1.push_back("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGG");
  lvl1.push_back("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGGGG");
  lvl1.push_back("BBBBBBBBBBBGGGGGGGGBBBBBBBBBBBBBBBGGGGGGGGG");
  lvl1.push_back("BBBBBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG");
  lvl1.push_back("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG");  
}

void batlvl2init()
{
  lvl2.push_back("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG");  
  lvl2.push_back("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG");  
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG");
  lvl2.push_back("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG");  
  lvl2.push_back("GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG");  
}

void lvlconstraints()
{
// if();
}

void batlvl1()
{
batlvl1init();
 for(int i=0; i<level1.rows;i++)
 {
  for(int j=0;j<level1.cols;j++)
   {
    drawlvlsquare(j,i,lvl1[i][j]);
   }
 }
}

void batlvl2()
{
batlvl2init();
 for(int i=0; i<level1.rows;i++)
 {
  for(int j=0;j<level1.cols;j++)
   {
    drawlvlsquare(j,i,lvl2[i][j]);
   }
 }
 checkmissile();
}


void lvl1_erase()
{
 lvl1.erase(lvl1.begin(),lvl1.end());
}

void lvl2_erase()
{
 lvl2.erase(lvl2.begin(),lvl2.end());
}
